### ISSUE TITLE
Crashes when there are console errors

### ISSUE THREAD

**Issue by tamj0rd2** [nils-hoyer/cypress-fail-on-console-error#1]
I'm using Cypress v6.0.0 and the tests seem to completely crash if there are console errors. I expected that the behaviour might be that you'd see an error, rather than the browser window crashing.

Anyway, thanks for creating this!

**Comment by nils-hoyer** [comment]
I can confirm that further tests in that specific spec file will be skipped. Further spec files will be executed properly. 
Is that the behavior you noticed?

I agree, this behavior is not ideal. I will work on a more robust version. Feel free to provide create a MR if you have in place already.

**Comment by nils-hoyer** [comment]
@tamj0rd2 I just released the version 1.1.0 which fixes the issue that further tests in the same spec file are skipped. Please let me know if you notice unexpected behavior.
