### ISSUE TITLE
errorMessage.match is not a function

### ISSUE THREAD

**Issue by wwei-flux** [nils-hoyer/cypress-fail-on-console-error#10]
I've been seeing this error when console.error is passed in non-strings.

**Comment by nils-hoyer** [comment]
Hey @wwei-flux, can you give me some more details on this?

do you mean the api usage, e.g.:
`const config = {
    excludeMessages: [ /this is a non string/i ]
};`

**or**

do you mean the underlaying sinon spy args message, e.g.:
`
spy.args[0][0] // console error message
//https://github.com/nils-hoyer/cypress-fail-on-console-error/blob/main/src/index.ts#L109
`

in the second case, please provide your cypress version, browser, browser version.

**Comment by wwei-flux** [comment]
Hi @nils-hoyer ,

I don't have a case that reproduces this now... from what I remember, it was from this line:

https://github.com/nils-hoyer/cypress-fail-on-console-error/blob/main/src/index.ts#L120

The `message` may not be a string. I think it happened when using something like `console.error(object)`.

Wei

**Comment by nils-hoyer** [comment]
Hi @wwei-flux, 

thank you for your response! I just fixed that issue in version 2.0.6.

https://github.com/nils-hoyer/cypress-fail-on-console-error/commit/4431c42993b629c9130a9782b74940e26696010e
