### ISSUE TITLE
Spies will not be resetted between cypress commands

### ISSUE THREAD

**Issue by nils-hoyer** [nils-hoyer/cypress-fail-on-console-error#102]
Case
plugin version 3.2.0
There are two tests in one spec

First test is failed because  of 422 validation error
Second test is failed because of that 
```
AssertionError: cypress-fail-on-console-error: 
"headers":{"normalizedNames":{},"lazyUpdate":null},"status":422,"statusText":"Unprocessable Entity","url"
```

Full stack trace of request is printed
I guess that is not expected behaviour, is it?

![image](https://user-images.githubusercontent.com/85738556/180857035-587699af-5626-4665-8b19-1ec08fe008d5.png)
![image](https://user-images.githubusercontent.com/85738556/180857233-e878230c-97a1-4c7f-952a-d8be6a901d3d.png)
<img width="703" alt="Screenshot 2022-07-25 at 22 19 13" src="https://user-images.githubusercontent.com/85738556/180857330-4aab7e50-da07-47ee-a935-13f95d2c1639.png">

_Originally posted by @rkhomi in https://github.com/nils-hoyer/cypress-fail-on-console-error/issues/90#issuecomment-1194512960_

**Comment by nils-hoyer** [comment]
Hi, 
many thanks for reporting this issue! I had a look into and found the root cause introduced by version 3.0.0: [commit](https://github.com/nils-hoyer/cypress-fail-on-console-error/compare/2.1.4...3.0.0#diff-3d2b59189eeedc2d428ddd632e97658fe310f587f7cb63b01f9b98ffc11c0197L46)

The issue should be fixed with version 3.2.1!

Git Release:
https://github.com/nils-hoyer/cypress-fail-on-console-error/releases/tag/3.2.1

NPM Release:
https://www.npmjs.com/package/cypress-fail-on-console-error/v/3.2.1

**Comment by romankhomitskyi** [comment]
@nils-hoyer Hi!
I was wondering whether plugin will still fail the test when we have 422 or 500 status code from browser API request?

I mean it's pretty nice feature an enables you to debug applications even better

So in my example here 
![image](https://user-images.githubusercontent.com/57874507/181230597-b67d358e-27b0-417f-93e0-61697bf99295.png)

my first test is failed because it didn't find locator
However I would like it to fail because of 422 status code and print response body

It is possible?

**Comment by nils-hoyer** [comment]
I agree with you, that observing network status codes would be a great improvement. 
AFAIK those information is not part of the window object, so I can not simply add spies to that objects.

There might be internal cypress API's or Events, which can be connected but I haven't looked into it. I assume cy.intercept() implementation would be a good starting point for analysis. 

Feel free to make an analysis on how it works in cypress and make a feature proposal.

**Comment by romankhomitskyi** [comment]
> I agree with you, that observing network status codes would be a great improvement. AFAIK those information is not part of the window object, so I can not simply add spies to that objects.
> 
> There might be internal cypress API's or Events, which can be connected but I haven't looked into it. I assume cy.intercept() implementation would be a good starting point for analysis.
> 
> Feel free to make an analysis on how it works in cypress and make a feature proposal.

I mean, your plugin was able to print failed request information. As it is described in this issue

```
AssertionError: cypress-fail-on-console-error: 
"headers":{"normalizedNames":{},"lazyUpdate":null},"status":422,"statusText":"Unprocessable Entity","url"
```

**Comment by nils-hoyer** [comment]
Hi @romankhomitskyi, it's now possible to also catch network errors. Its published as a new module: https://github.com/nils-hoyer/cypress-fail-on-network-request
