### ISSUE TITLE
Package 'type-detect' is used in project but not listed as prod dependency (causing package to fail under non-hoisting package managers)

### ISSUE THREAD

**Issue by gregjacobs** [nils-hoyer/cypress-fail-on-console-error#196]
The package relies on the `type-detect` 3rd party dependency, but this dependency is not listed in the `package.json` file.

This causes `cypress-fail-on-console-error` to fail when installed with a strict package manager like `pnpm`, which does not hoist transitive dependencies to the top-level `node_modules` directory. (`type-detect` is a transitive dependency of `chai`)

Fix should be simple: just add `type-detect` under `dependencies` in package.json

**Comment by nils-hoyer** [comment]
Hi @gregjacobs,
thanks for the hint. I just added the type-detect under dependencies. The fix will be released in version [4.0.3](https://github.com/nils-hoyer/cypress-fail-on-console-error/releases/tag/4.0.3).

**Comment by gregjacobs** [comment]
Thanks @nils-hoyer, much appreciated!

Best,
Greg
