### ISSUE TITLE
Getting [Function] is not a spy or a call to a spy!

### ISSUE THREAD

**Issue by fes300** [nils-hoyer/cypress-fail-on-console-error#2]
Hi @nils-hoyer and thanks for the nice lib :) 

unfortunately, it is not working for me (cypress 6.0.1) can't figure out why...

![image](https://user-images.githubusercontent.com/10383300/102803748-0e213480-43b9-11eb-9fb3-8701c17adf3d.png)

**Comment by nils-hoyer** [comment]
Hi @fes300, thanks for reporting!

Can you please provide your cypress test code, so I can have a look on how your test case differ from the integration tests:
https://github.com/nils-hoyer/cypress-fail-on-console-error/tree/main/cypress/integration

cheers

**Comment by nils-hoyer** [comment]
I will close the Issue due to inactivity.
