### ISSUE TITLE
bug: Webpack Compilation Error

### ISSUE THREAD

**Issue by lucasdonato** [nils-hoyer/cypress-fail-on-console-error#223]
Hi, I'm having this error when using the failOnConsoleError plugin together with webpack when running the tests through the terminal.

![image](https://github.com/nils-hoyer/cypress-fail-on-console-error/assets/12953400/ecaeffe5-0b0a-46cd-b63e-fa52f2f09a9e)

 "webpack": "5.88.2"
"cypress-fail-on-console-error": "4.0.3"

In the **cypress.config.js** file I just need to comment this line **import failOnConsoleError from 'cypress-fail-on-console-error'** and the webpack works.

**Comment by work933k** [comment]
I think it's relevant to give the version of Cypress you are using...

This works for me in a NX-workspace, maybe it gives you a hint to resolve your issue:
```package.json
    "cypress": "12.14.0",
    "cypress-fail-on-console-error": "4.0.3",

    implicit: webpack@5.87.0
```
```apps/dummy-app-e2e/src/support/index.ts
import failOnConsoleError, { Config } from 'cypress-fail-on-console-error';

const config: Config = {
  consoleMessages: [],
};
failOnConsoleError(config);
```

```apps/dummy-app-e2e/cypress.config.ts
import { defineConfig } from 'cypress';

module.exports = defineConfig({
  ...
  e2e: {
    testIsolation: false,
    experimentalRunAllSpecs: true,
    setupNodeEvents(on, config) {
      return config;
    },
    specPattern: './src/integration/**/*.cy.{js,jsx,ts,tsx}',
    supportFile: './src/support/index.ts',
  },
});
````
```apps/dummy-app-e2e/tsconfig.json
{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "sourceMap": false,
    "outDir": "../../dist/out-tsc",
    "allowJs": true,
    "types": ["cypress", "node"],
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitOverride": true,
    "noPropertyAccessFromIndexSignature": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src/**/*.ts", "src/**/*.js", "cypress.config.ts"]
}
```

**Comment by nils-hoyer** [comment]
Hi @lucasdonato,
as of today, `os` package is no dependency anymore. Please verify with version [5.0.0](https://www.npmjs.com/package/cypress-fail-on-console-error/v/5.0.0). Please give some feedback.

Cheers

**Comment by lucasdonato** [comment]
Hi @nils-hoyer , it worked perfectly! Thanks.
