### ISSUE TITLE
Unclear failure screenshot

### ISSUE THREAD

**Issue by work933k** [nils-hoyer/cypress-fail-on-console-error#224]
Hi Nils,
I really appreciate the functionality this package brings.
In our CI pipeline i see that the "fail-on-console-error" gets correctly triggered, but it's not very clear by looking at the screenshot. It's because i know what to look for, but new developers dont recognize it given the screenshot.
What am i doing wrong here? Is this something you recognize?
![image](https://github.com/nils-hoyer/cypress-fail-on-console-error/assets/132996099/2983bc06-2894-4e9a-8e6f-8314566f5e45)

**Comment by nils-hoyer** [comment]
Thanks for reporting the issue. I can verify when running cypress via `cypress run` the screenshot is not showing the Assertion Error. When running cypress via `cypress open` the UI is showing the Assertion Error properly.

As a workaround I can recommend to use the cypress test execution log instead.
<img width="952" alt="Bildschirmfoto 2023-08-08 um 12 17 53" src="https://github.com/nils-hoyer/cypress-fail-on-console-error/assets/2456847/0a45a51e-9a73-4a11-8ae4-bf675542fcf5">

**Comment by work933k** [comment]
Thanks!
