### ISSUE TITLE
Does not fail on request that are running in 40x or 50x

### ISSUE THREAD

**Issue by p5hema2** [nils-hoyer/cypress-fail-on-console-error#25]
The Plugin works great on Javascript Errors which are thrown, but requests that are running in an Error are not catched even if there is an Error displayed in console.

**Comment by nils-hoyer** [comment]
I do agree with you. This plugin can observe everything coming from console.error(), console.warn() and console.info() for you. I will make it more explicit from the docs. Thanks.
