### ISSUE TITLE
Exclude specific messages per test

### ISSUE THREAD

**Issue by mirobo** [nils-hoyer/cypress-fail-on-console-error#47]
Hey there

I've stumbled upon the limitation that you cannot exclude specific messages on a "per test" basis.

Sometimes you want the application to log an error and you want to ignore that error.

After trying out different things with the plugin I came up with this solution:

support/index.ts
```
if (Cypress.env('FAIL_ON_CONSOLE_ERROR')) {

  const excludeMessagesDefault = [
    /Invalid Host\/Origin header/,
    /\[WDS] Disconnected!/
  ];

  Cypress.on('window:before:load', (win) => {
    cy.spy(win.console, 'error').as('consoleError');
  });

  afterEach(() => {
    const exclusions: RegExp[] = Cypress.env('excludeMessages')
      ? [...excludeMessagesDefault, ...Cypress.env('excludeMessages')]
      : excludeMessagesDefault;
    cy.log(`analyzing console errors with exclusions:\r\n${exclusions.join('\r\n')}`);
    cy.get('@consoleError', { timeout: 4000 }).should((sinonSpy) => {
      const spy = sinonSpy as unknown as Agent<sinon.SinonSpy>;
      const consoleErrors: string[] = [];
      spy.getCalls().forEach((spyCall) => {
        const consoleErrorText = spyCall.lastArg.toString();
        const ignoreError = exclusions.some((excludeMessage) => excludeMessage.test(consoleErrorText));
        if (!ignoreError) {
          consoleErrors.push(consoleErrorText);
        }
      });
      expect(consoleErrors.length).to.eq(0, `verify that no console errors occurred\r\n${consoleErrors.join('\r\n')}`);
    });
  });
}
```

test example
```
it('my test', {
  env: {
   excludeMessages: [/my message to exclude/]
  }
}, () => {
 // ...
});

```

I didn't address the configuration of log levels, but this seems easy to configure as well.

What issues do you see in this solution compared to yours?

What I know of:
- The test doesn't end on the first console error; it collects them all (which MAY be better, so you can collect all errors in one go. But it could also lead to follow up errors being reported)
- Once a test failed due to the assertion in afterEach, all remaining tests in the spec will be skipped (works as designed by Cypress). Not ideal, but not much I can do about it. Don't think the current behaviour is going to be changed.
- Every test needs to start with cy.visit() or the window:before:load hook will be meaningless; This means you cannot create a test which starts with a single visit and then run multiple tests on the same page. I know it shouldn't be done this way, but imagine having a page that loads very slow and you just take the risk of having side effects in later tests (from previous tests). One workaround would be to just include all actions/assertions in the same test but then you loose the structure of the tests (if you have very long tests you might want to split them up)

**Comment by nils-hoyer** [comment]
Hi @mirobo , 
looks like a solid solution with its own pros and cons. I am glad that I did inspire you with my plugin :-)
