### ISSUE TITLE
sinon and sinon-chai should be listed as dependencies (webpack compilation error)

### ISSUE THREAD

**Issue by kaiyoma** [nils-hoyer/cypress-fail-on-console-error#6]
I tried using this plugin and on my first run, I got this:

```
Oops...we found an error preparing this test file:

  cypress/support/index.js

The error was:

Error: Webpack Compilation Error
./node_modules/cypress-fail-on-console-error/dist/index.js
Module not found: Error: Can't resolve 'sinon' in '.../node_modules/cypress-fail-on-console-error/dist'
resolve 'sinon' in '.../node_modules/cypress-fail-on-console-error/dist'
  Parsed request is a module
```

If your plugin requires sinon to run, it should be listed as a dependency, not a dev dependency.

After fixing that (by adding sinon to my package.json), I got the same error for sinon-chai. Both packages should be dependencies if they're required at runtime.

**Comment by nils-hoyer** [comment]
fixed with version 2.0.4:
https://github.com/nils-hoyer/cypress-fail-on-console-error/releases/tag/2.0.4

commit hash: https://github.com/nils-hoyer/cypress-fail-on-console-error/commit/8c8425bef1e0c885b0885a66ea9b6362e0a19ca0
