### ISSUE TITLE
Fails on excluded errorr

### ISSUE THREAD

**Issue by rkhomi** [nils-hoyer/cypress-fail-on-console-error#87]
AssertionError: console match found: expected 'IntegrationError: The selector you sp…' to be undefined

```
const config = {
	excludeMessages: [
		'The selector you specified (#cardStripe) applies to no DOM elements that are currently on the page.',
	],
	includeConsoleTypes: [consoleType.ERROR],
};
failOnConsoleError(config);
```

"cypress-fail-on-console-error": "^3.0.0"
"cypress": "9.6.1"

**Comment by nils-hoyer** [comment]
From the docs: 
ExludeMessages, "String parameter will be interpreted as regular Expression". By it's nature special chars have to be escaped. Here is am example to make it work: https://regex101.com/r/9QmExF/1

**Comment by nils-hoyer** [comment]
> <img alt="Screenshot 2022-06-28 at 10 35 23" width="857" src="https://user-images.githubusercontent.com/85738556/176120906-7a4ef783-53cd-43be-8342-50c3ce9d34e2.png">
> 
> Also it does not displays full error message

Thanks for reporting @rkhomi.
I created a bug ticket and will look into it.

**Comment by romankhomitskyi** [comment]
> From the docs: ExludeMessages, "String parameter will be interpreted as regular Expression". By it's nature special chars have to be escaped. Here is am example to make it work: https://regex101.com/r/9QmExF/1

Thank you
