### ISSUE TITLE
Long error message will be cut off 

### ISSUE THREAD

**Issue by nils-hoyer** [nils-hoyer/cypress-fail-on-console-error#90]
<img width="857" alt="Screenshot 2022-06-28 at 10 35 23" src="https://user-images.githubusercontent.com/85738556/176120906-7a4ef783-53cd-43be-8342-50c3ce9d34e2.png">
Also it does not displays full error message

_Originally posted by @rkhomi in https://github.com/nils-hoyer/cypress-fail-on-console-error/issues/87#issuecomment-1168348740_

**Comment by kaiyoma** [comment]
Yes, we're running into this problem too, ever since upgrading to Cypress 10 and the latest version of this plugin. Error messages are cut off at a really short length, which makes them mostly useless. Example:

```
02:26:31    1) General > Navigation
02:26:31         should be able to navigate among the modules, forwards and backwards:
02:26:31       AssertionError: console match found: expected 'Warning: Can\'t perform a React state…' to be undefined
02:26:31        at $Cypress.eval (http://localhost:4001/__cypress/tests?p=cypress/support/e2e.js:28811:68)
```

**Comment by magnattic** [comment]
Does any have a workaround?

**Comment by nils-hoyer** [comment]
I could not reproduce the cut off locally, even with with 50.000 chars the message was not cut off. I assume its related to some special chars sequence. 

Nevertheless I replaced chai expect() with AssertionError() to "shift" around this issue. 

@magnattic @kaiyoma  
please verify the issue is fixed: 
grab the [index.js](https://github.com/nils-hoyer/cypress-fail-on-console-error/blob/90-long-error-will-be-cut-off/dist/index.js) from the branch, paste it to your project/node_modules/cypress-fail-on-console-error/dist/index.js and run the test with cut off error message.

**Comment by kaiyoma** [comment]
@nils-hoyer I tried your instructions and I'm getting a runtime error:

```
Error: Build failed with 1 error:
../../common/temp/node_modules/.pnpm/cypress-fail-on-console-error@3.0.0/node_modules/cypress-fail-on-console-error/dist/index.js:32:19: ERROR: Could not resolve "os"
    at failureErrorWithLog (C:\Work\event-viewer\common\temp\node_modules\.pnpm\esbuild@0.14.38\node_modules\esbuild\lib\main.js:1603:15)
    at C:\Work\event-viewer\common\temp\node_modules\.pnpm\esbuild@0.14.38\node_modules\esbuild\lib\main.js:1249:28
    at runOnEndCallbacks (C:\Work\event-viewer\common\temp\node_modules\.pnpm\esbuild@0.14.38\node_modules\esbuild\lib\main.js:1034:63)
    at buildResponseToResult (C:\Work\event-viewer\common\temp\node_modules\.pnpm\esbuild@0.14.38\node_modules\esbuild\lib\main.js:1247:7)
    at C:\Work\event-viewer\common\temp\node_modules\.pnpm\esbuild@0.14.38\node_modules\esbuild\lib\main.js:1356:14
    at C:\Work\event-viewer\common\temp\node_modules\.pnpm\esbuild@0.14.38\node_modules\esbuild\lib\main.js:666:9
    at handleIncomingPacket (C:\Work\event-viewer\common\temp\node_modules\.pnpm\esbuild@0.14.38\node_modules\esbuild\lib\main.js:763:9)
    at Socket.readFromStdout (C:\Work\event-viewer\common\temp\node_modules\.pnpm\esbuild@0.14.38\node_modules\esbuild\lib\main.js:632:7)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
```

I see this error in my Cypress output:

```
X [ERROR] Could not resolve "os"

    ../../common/temp/node_modules/.pnpm/cypress-fail-on-console-error@3.0.0/node_modules/cypress-fail-on-console-error/dist/index.js:32:19:
      32 │ var os_1 = require("os");
         ╵                    ~~~~

  The package "os" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
```

For reference, I'm already setting `platform: "node"`.

**Comment by nils-hoyer** [comment]
Hi @kaiyoma, 
When I set up a fresh new cypress project with cypress-fail-on-console-error 3.1 and replace the index.js file it works for me. Package OS is part of Node since version 0.7.8. I assume it's related to your project setup.

**Comment by rkhomi** [comment]
![image](https://user-images.githubusercontent.com/85738556/180438272-a8e25f55-256a-4761-ae29-e3f1d5c55507.png)

**Comment by nils-hoyer** [comment]
@rkhomi you are still using 3.1. I can identify that, because the assertion message slightly changed. I will publish the change in a release and based on that you still can get feedback.

**Comment by nils-hoyer** [comment]
The issue should be fixed with version 3.2.0.

Git Commit:
https://github.com/nils-hoyer/cypress-fail-on-console-error/commit/7485d76907e8ad7a3fac7c7756c21a16aedf3dda

Git Release:
https://github.com/nils-hoyer/cypress-fail-on-console-error/releases/tag/3.2.0

NPM Release:
https://www.npmjs.com/package/cypress-fail-on-console-error/v/3.2.0

**Comment by rkhomi** [comment]
Case
plugin version 3.2.0
There are two tests in one spec

First test is failed because  of 422 validation error
Second test is failed because of that 
```
AssertionError: cypress-fail-on-console-error: 
"headers":{"normalizedNames":{},"lazyUpdate":null},"status":422,"statusText":"Unprocessable Entity","url"
```

Full stack trace of request is printed
I guess that is not expected behaviour, is it?

![image](https://user-images.githubusercontent.com/85738556/180857035-587699af-5626-4665-8b19-1ec08fe008d5.png)
![image](https://user-images.githubusercontent.com/85738556/180857233-e878230c-97a1-4c7f-952a-d8be6a901d3d.png)
<img width="703" alt="Screenshot 2022-07-25 at 22 19 13" src="https://user-images.githubusercontent.com/85738556/180857330-4aab7e50-da07-47ee-a935-13f95d2c1639.png">

**Comment by rkhomi** [comment]
Previously plugin does not fail the tests when API errors occur like 422 or 500 
Does it fail now?

**Comment by nils-hoyer** [comment]
> Case plugin version 3.2.0 There are two tests in one spec
> 
> First test is failed because of 422 validation error Second test is failed because of that
> 
> ```
> AssertionError: cypress-fail-on-console-error: 
> "headers":{"normalizedNames":{},"lazyUpdate":null},"status":422,"statusText":"Unprocessable Entity","url"
> ```
> 
> Full stack trace of request is printed I guess that is not expected behaviour, is it?
> 
> ![image](https://user-images.githubusercontent.com/85738556/180857035-587699af-5626-4665-8b19-1ec08fe008d5.png) ![image](https://user-images.githubusercontent.com/85738556/180857233-e878230c-97a1-4c7f-952a-d8be6a901d3d.png) <img alt="Screenshot 2022-07-25 at 22 19 13" width="703" src="https://user-images.githubusercontent.com/85738556/180857330-4aab7e50-da07-47ee-a935-13f95d2c1639.png">

out of scope to the topic of this ticket.

**Comment by nils-hoyer** [comment]
I will close this ticket and assume it is fixed by the replacement chai.expect() with chai.assertionError(). Please reopen if the error persist in latest version.

**Comment by kaiyoma** [comment]
@nils-hoyer I'm still having problems getting this new version to run, because of the new dependency on `os`. There's a discussion here too: https://github.com/evanw/esbuild/issues/2409

It's a bit unclear how to proceed here. Cypress + @bahmutov/cypress-esbuild-preprocessor + cypress-fail-on-console-error no longer works.

**Comment by romankhomitskyi** [comment]
> @nils-hoyer I'm still having problems getting this new version to run, because of the new dependency on `os`. There's a discussion here too: [evanw/esbuild#2409](https://github.com/evanw/esbuild/issues/2409)
> 
> It's a bit unclear how to proceed here. Cypress + @bahmutov/cypress-esbuild-preprocessor + cypress-fail-on-console-error no longer works.

There is a new version of plugin, so just upgrade your dependency as you do it usually

**Comment by kaiyoma** [comment]
@romankhomitskyi Yes, that's what I'm talking about. Version 3.2.0 introduces a dependency on `os` and that's breaking things. Unless you're saying that the dependency was removed in 3.2.1?

**Comment by romankhomitskyi** [comment]
> @romankhomitskyi Yes, that's what I'm talking about. Version 3.2.0 introduces a dependency on `os` and that's breaking things. Unless you're saying that the dependency was removed in 3.2.1?

Nope

**Comment by kaiyoma** [comment]
Okay, I figured out the esbuild-Node-polyfill situation (see https://github.com/evanw/esbuild/issues/2409#issuecomment-1198446562 for details) and now I can see that the new version of this plugin does indeed fix the original problem. I can see full error messages again! Thanks @nils-hoyer for the fix.

**Comment by romankhomitskyi** [comment]
Yeah, I can confirm that issue is fixed, many thanks
